{
 "title": "Alert History",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource_prom", "label": "Prometheus", "query": "prometheus" },
   { "name": "datasource_loki", "label": "Loki", "query": "loki" },
   {
    "name": "alertname",
    "query": "label_values(ALERTS, alertname)"
   },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Alert Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{alertname=~\"$alertname\", alertname!~\"InfoInhibitor\", alertstate=\"firing\"}",
     "legendFormat": "{{alertname}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Overall CPU Resources (Namespace: $namespace)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$namespace\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"$namespace\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Overall RAM Resources (Namespace: $namespace)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", namespace=~\"$namespace\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$namespace\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"$namespace\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Alert Logs (Namespace: $namespace | Search: $alertname)",
   "type": "logs",
   "gridPos": { "x": 0, "y": 42, "w": 24, "h": 14 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\"} | pod=~\".*\" |~ \"$alertname\"",
     "legendFormat": "Logs"
    }
   ]
  }
 ]
}