{
 "title": "Loki / AlertSnitch Alert History Overview",
 "description": "Ingests Prometheus alerts and poops them into a backend storage for offline analysis",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "loki_datasource", "query": "loki" },
   { "name": "label_filter" },
   { "name": "content_filter", "label": "content_filter" }
  ]
 },
 "panels": [
  {
   "title": "Top 10 Triggered Alerts",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{alert_status=\"firing\"} |= `$content_filter` | json alertname=\"alert.labels.alertname\", fingerprint=\"alert.fingerprint\", startsAt=\"alert.startsAt\""
    }
   ]
  },
  {
   "title": "Average Mean time to Resolved (MTTR)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(alertname, startsAt, endsAt, fingerprint) (count_over_time({alert_status=\"resolved\"} |= `$content_filter` | json endsAt=\"alert.endsAt\", startsAt=\"alert.startsAt\", alertname=\"alert.labels.alertname\", fingerprint=\"alert.fingerprint\" [$__range]))"
    }
   ]
  },
  {
   "title": "Triggered Alerts by Severity",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(count_over_time({alert_status=\"firing\"} |= \"$content_filter\" | json alertname=\"alert.labels.alertname\", fingerprint=\"alert.fingerprint\", startsAt=\"alert.startsAt\" [$__range])) by (alertname, fingerprint, startsAt, severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Triggered Alerts by Priority",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "count(sum(count_over_time({alert_status=\"firing\"} |= \"$content_filter\"  | json alertname=\"alert.labels.alertname\", fingerprint=\"alert.fingerprint\", startsAt=\"alert.startsAt\" [$__range])) by (alertname, fingerprint, startsAt, priority)) by (priority)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Total number of Alert Sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "count(sum(count_over_time({alert_status=\"firing\"} |= \"$content_filter\" | json alertname=\"alert.labels.alertname\", fingerprint=\"alert.fingerprint\", startsAt=\"alert.startsAt\" [$__range])) by (alertname, fingerprint, startsAt))"
    }
   ]
  },
  {
   "title": "Trigged Alert Statistics",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 15 },
   "targets": [
    {
     "expr": "count (sum(count_over_time({alert_status=\"firing\"} |= \"$content_filter\" | json alertname=\"alert.labels.alertname\", fingerprint=\"alert.fingerprint\", startsAt=\"alert.startsAt\" [$__range])) by (alertname, fingerprint, startsAt, severity)) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Total number of Alert Resolved",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "count(sum by(alertname, startsAt, fingerprint) (count_over_time({alert_status=\"resolved\"} |= `$content_filter` | json startsAt=\"alert.startsAt\", alertname=\"alert.labels.alertname\", fingerprint=\"alert.fingerprint\" [$__range])))"
    }
   ]
  },
  {
   "title": "Resolved Alert statistics",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "expr": "count(sum by(alertname, startsAt, fingerprint, severity) (count_over_time({alert_status=\"resolved\"} |= `$content_filter` | json startsAt=\"alert.startsAt\", alertname=\"alert.labels.alertname\", fingerprint=\"alert.fingerprint\" [$__range]))) by (severity)",
     "legendFormat": "{{serverity}}"
    }
   ]
  },
  {
   "title": "Triggered Alert Trend by Severity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "count(sum(count_over_time({alert_status=\"firing\"} |= \"$content_filter\" | json alertname=\"alert.labels.alertname\", fingerprint=\"alert.fingerprint\", startsAt=\"alert.startsAt\" [$__auto])) by (alertname, fingerprint, startsAt, severity)) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Resolved Alert Trend by Severity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "count(sum(count_over_time({alert_status=\"resolved\"} |= \"$content_filter\" | json alertname=\"alert.labels.alertname\", fingerprint=\"alert.fingerprint\", startsAt=\"alert.startsAt\" [$__auto])) by (alertname, fingerprint, startsAt, severity)) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Alerts not Resolved",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{alert_status=~\".+\"} |= \"$content_filter\" | json"
    }
   ]
  },
  {
   "title": "Alert Resolved",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "{alert_status=\"resolved\"} |= \"$content_filter\" | json"
    }
   ]
  },
  {
   "title": "History Alert Details",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{alert_status=~\".+\"} |= \"$content_filter\" | json"
    }
   ]
  }
 ]
}